# Import packages

```{r}

rm(list = ls())
library(sf)
library(sp)
library(maps)
library(gstat)
library(dplyr)
library(mapdata)
library(ggplot2)
library(reshape2)
library(spacetime)
source("../R/geomatching.R")
```

# Import data

-   **AQ_EEA_NO2**: NO~2~ point data measured from air quality monitoring data.

-   **AQ_CAMS_N02**: NO~2~ gridded data (0.01**°** x 0.01**°**) obtained from CAMS mathematical model.

```{r}

# CSV data (.csv)
AQ_EEA_NO2 <- read.csv("AQ_EEA_NO2.csv")

# R environment (.RData)
load("AQ_CAMS_NO2.RData")
```

# 1^st^ step: `geomatching`

## Configuration

```{r}

data_dict <- list(
  "AQ_EEA_NO2" = list(
    "data" = AQ_EEA_NO2,
    "format" = "xyt",
    "type" = "points",
    "crs" = 4979
  ),
  "AQ_CAMS_NO2" = list(
    "data" = AQ_CAMS_NO2,
    "format" = "matrix",
    "type" = "grid",
    "crs" = 4326
  )
)

data_ls <- list()
settings = list(
  "format"=c(),
  "type"=c(),
  "crs"=c()
)
for (i in seq_along(data_dict)) {
  data_ls[[i]] <- data_dict[[i]]$data
  settings$format[[i]] <- data_dict[[i]]$format
  settings$type[[i]] <- data_dict[[i]]$type
  settings$crs[[i]] <- data_dict[[i]]$crs
}
```

## Run

```{r}
res_geomatch <- geomatching(
  data=data_ls,
  settings = list(
    "format"=settings$format,
    "type"=settings$type,
    "crs"=settings$crs
  )
)

# rename columns
res_geomatch <- res_geomatch %>%
  rename(
    altitude = Altitude,
    AQ_CAMS_NO2 = matrix_2
  )
```

## Data visualization

```{r}

for (var in c("AQ_EEA_NO2", "AQ_CAMS_NO2", "altitude")) {
  
  p <- ggplot() +
    geom_map(
      data = map_data("italy"),
      map = map_data("italy"),
      aes(map_id = region),
      fill = "lightgrey",
      color = "black",
      linewidth = 0.1,
      alpha=.9
    ) + 
    geom_point(
      data = res_geomatch[res_geomatch$time==res_geomatch$time[1],],
      aes(x = longitude, y = latitude, color = .data[[var]]),
      size = 5,
      
    ) +
    labs(
      title = sprintf("Geographical map of %s", var),
      subtitle = "Output of geomatching",
      x = "Longitude",
      y = "Latitude"
    ) + 
    scale_color_viridis_c(
      option = "C"
    ) +
    theme(
      legend.title = element_blank(),
      plot.title = element_text(face = "bold")
    ) 
  print(p)
}
```
